name: Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Prepare Release Archive
      run: |
        cd download
        zip -r download-${{ env.SHA_SHORT }}.zip .

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: download-${{ env.SHA_SHORT }}.zip
        tag_name: release-${{ env.SHA_SHORT }}
        body: |
            ${{ github.event.head_commit.message }}